# Generated by Django 4.0.6 on 2022-08-02 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0003_rename_subeject_lesson_subeject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audience_name',
            field=models.CharField(choices=[(101, '101'), (102, '102'), (103, '103'), (104, '104'), (105, '105'), (106, '106'), (107, '107'), (108, '108')], default=101, max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='shared.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subeject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjetcs', to='shared.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher_full_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_day',
            field=models.CharField(choices=[('MONDAY', 'monday'), ('TUESDAY', 'tuesday'), ('WEDNESDAY', 'wednesday'), ('THURSDAY', 'thursday'), ('FRIDAY', 'friday'), ('SATURDAY', 'saturday')], default='MONDAY', max_length=50),
        ),
    ]
