# Generated by Django 4.0.6 on 2022-08-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_lesson_audience_name_alter_lesson_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audience_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiences', to='timetable.audience'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekdays', to='timetable.weekday'),
        ),
    ]
