# Generated by Django 4.0.6 on 2022-08-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_lesson_audience_name_alter_lesson_week_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='week_day',
            new_name='today',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='subeject_name',
            new_name='today_subeject',
        ),
    ]
