# Generated by Django 4.0.6 on 2022-08-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_delete_subject'),
        ('timetable', '0008_remove_lesson_today_lesson_today_is_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher_full_name',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shared.subjectteacherrelation'),
        ),
    ]
