# Generated by Django 4.0.6 on 2022-08-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_remove_lesson_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='audience_name',
        ),
    ]
