# Generated by Django 4.0.6 on 2022-08-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_remove_lesson_audience_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekDay',
        ),
    ]
