# Generated by Django 4.1 on 2022-08-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_delete_weekday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audience',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
    ]
