# Generated by Django 4.0.6 on 2022-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacherRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject_name', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
