# Generated by Django 4.0.6 on 2022-08-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_subjectteacherrelation_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectteacherrelation',
            name='audience',
            field=models.CharField(choices=[('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109'), ('110', '110')], default='101', max_length=150),
        ),
    ]
